const express = require('express');
const router = express.Router();
const orderController = require('../controllers/orderController');
const authMiddleware = require('../middleware/authMiddleware');
router.use(authMiddleware);
router.get('/payment-providers', orderController.getPaymentProviders);
router.get('/', orderController.getOrders);
router.get('/:id', orderController.getOrder);
router.post('/', orderController.createOrder);
router.post('/:id/verify-payment', orderController.verifyPayment);
module.exports = router;
